# stack_map.py — GENERATED FILE, DO NOT EDIT BY HAND.
#
# Extension/filename -> ergonomic stack label for the repo-index. Curated: the
# top ~40 common language/tooling stacks, with the labels the tool already uses
# (python/node/dotnet/sql/typescript/go/rust/terraform/docker/...).
#
# Regenerate with:
#     python3 tools/gen_stack_map.py
# (the STACKS table in tools/gen_stack_map.py is the source of truth — no external
# input, so this reproduces byte-for-byte). Unknown extensions are intentionally
# absent; repo_index degrades gracefully on anything not listed here.
#
# Pure stdlib: plain dict literals, no imports, no runtime code, no network.
"""Curated extension/filename -> stack-label lookups (generated)."""

EXT_TO_STACK = {
    '.bash': 'shell',
    '.c': 'c',
    '.c++': 'cpp',
    '.cc': 'cpp',
    '.cjs': 'node',
    '.clj': 'clojure',
    '.cljc': 'clojure',
    '.cljs': 'clojure',
    '.cpp': 'cpp',
    '.cr': 'crystal',
    '.cs': 'dotnet',
    '.css': 'css',
    '.cts': 'typescript',
    '.cxx': 'cpp',
    '.dart': 'dart',
    '.edn': 'clojure',
    '.elm': 'elm',
    '.erl': 'erlang',
    '.ex': 'elixir',
    '.exs': 'elixir',
    '.fs': 'dotnet',
    '.fsx': 'dotnet',
    '.go': 'go',
    '.gql': 'graphql',
    '.gradle': 'groovy',
    '.graphql': 'graphql',
    '.groovy': 'groovy',
    '.h': 'c',
    '.hh': 'cpp',
    '.hpp': 'cpp',
    '.hrl': 'erlang',
    '.hs': 'haskell',
    '.htm': 'html',
    '.html': 'html',
    '.hxx': 'cpp',
    '.java': 'java',
    '.jl': 'julia',
    '.js': 'node',
    '.jsx': 'node',
    '.ksh': 'shell',
    '.kt': 'kotlin',
    '.kts': 'kotlin',
    '.lhs': 'haskell',
    '.lua': 'lua',
    '.m': 'objective-c',
    '.mjs': 'node',
    '.mk': 'make',
    '.ml': 'ocaml',
    '.mli': 'ocaml',
    '.mm': 'objective-c',
    '.mts': 'typescript',
    '.nim': 'nim',
    '.nims': 'nim',
    '.perl': 'perl',
    '.php': 'php',
    '.phtml': 'php',
    '.pl': 'perl',
    '.pm': 'perl',
    '.proto': 'protobuf',
    '.ps1': 'powershell',
    '.psd1': 'powershell',
    '.psm1': 'powershell',
    '.py': 'python',
    '.pyi': 'python',
    '.pyw': 'python',
    '.r': 'r',
    '.rake': 'ruby',
    '.rb': 'ruby',
    '.rs': 'rust',
    '.sass': 'scss',
    '.sc': 'scala',
    '.scala': 'scala',
    '.scss': 'scss',
    '.sh': 'shell',
    '.sol': 'solidity',
    '.sql': 'sql',
    '.svelte': 'svelte',
    '.swift': 'swift',
    '.tf': 'terraform',
    '.tfvars': 'terraform',
    '.ts': 'typescript',
    '.tsx': 'typescript',
    '.vb': 'dotnet',
    '.vue': 'vue',
    '.zig': 'zig',
    '.zsh': 'shell',
}

FILENAME_TO_STACK = {
    'Dockerfile': 'docker',
    'GNUmakefile': 'make',
    'Gemfile': 'ruby',
    'Makefile': 'make',
    'Rakefile': 'ruby',
    'go.mod': 'go',
}
