"""brain-station — the publish engine (private vault -> shared brain mirror).

PROVENANCE: ported in 3.0.0 Phase 4 (chunk 4b) from the brain source tree's
``scripts/publish.py`` @ 0.14.0.

The shared brain is a per-person mirror repo: org-readable, owner-writable. It
holds the notes the owner chooses to publish. Publishing is **opt-IN**: a note
in ``<vault>/notes/`` publishes ONLY when its frontmatter carries
``publish: true``. A note with no such field — which is every note by default —
stays in the private vault. ``memory/``, ``raw/``, ``plans/`` and ``reports/``
NEVER publish; this engine only ever reads ``notes/``.

Before a note is mirrored it passes a blocking **publish-lint** (per note): a
note that contains a local home-directory absolute path, a UUID-shaped session
id, or any secret pattern from ``brain.heal_lint`` is SKIPPED with a loud
per-note reason — never transformed silently — and the run continues. The
summary lists every blocked note.

Sync is true mirror semantics: eligible+clean notes are copied byte-exact
(preserving filenames), an ``INDEX.md`` is regenerated from the published notes,
and a ``README.md`` header (read-only-for-others notice) is written once if
absent. The run is idempotent — unchanged input performs zero writes. When the
mirror is a git repo the sync lands as ONE commit ``publish: <n> notes
(<date>)``; it is never pushed (the owner/hub pushes).

THE DELETION SWEEP IS THREE-WAY, and that is the safety property of opt-in.
Mirror semantics would otherwise mean the first run after the opt-out→opt-in
flip erases every previously-published note, because none of them carry the new
field yet. So a mirror note whose source is GONE is deleted, one whose source is
BLOCKED by publish-lint is deleted (a leak must come out), but one whose source
is still there and still clean and merely has no ``publish: true`` is KEPT and
REPORTED as ``withdrawn``. Only an explicit ``withdraw=True`` / ``--withdraw``
actually drops those. A default run never silently un-publishes anything.

Layer rule: brain may import core and its own siblings, never board. Stdlib +
the sibling ``config`` / ``notes`` / ``heal_lint`` modules only.

Pure stdlib, Python 3.9+.
"""
import argparse
import datetime
import re
import subprocess
import sys
from pathlib import Path

from . import config
from . import notes
from . import heal_lint  # reuse the exact secret-pattern set (heal_lint.SECRET_RX) — one source of truth


class PublishError(Exception):
    """A git failure during the mirror commit (loud, per the write-path posture)."""


# Publish-lint patterns. The home-path regex is built via a character class so the
# guard's own source line does not contain the forbidden home-path literal that a
# shipped module must never carry. Matches macOS and Linux home-directory
# absolute paths.
_HOME_ABS_RX = re.compile(r"/(?:Users|home)/\S")
_UUID_RX = re.compile(
    r"\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\b")
# a bare GUID is often org reference material (ADO namespace ids, resource ids);
# only a UUID in *session* context is a leak — gate on the surrounding line.
_SESSION_CTX_RX = re.compile(r"session|originSessionId|transcript|--resume|claude --", re.I)


def lint_note(text):
    """Return a list of blocking reasons for ``text`` (empty = clean to publish).

    Scans the WHOLE note (frontmatter + body), not just prose: a public mirror
    must not leak a home path or session id even inside a code fence."""
    reasons = []
    if _HOME_ABS_RX.search(text):
        reasons.append("contains a local home-directory absolute path")
    for line in text.splitlines():
        if _UUID_RX.search(line) and _SESSION_CTX_RX.search(line):
            reasons.append("contains a UUID-shaped session id")
            break
    if heal_lint.SECRET_RX.search(text):
        reasons.append("contains a secret-shaped string (brain.heal_lint pattern)")
    return reasons


def _flag(fm, key):
    """Read one of the two share switches. Absent = OFF; only a literal ``true``
    (any case, quoted or not) enables. The implementation is ``notes.switch`` —
    ONE reader for the whole plane, so publish and promote can never disagree
    about what a switch means."""
    return notes.switch(fm, key)


def _index_content(published_meta):
    """Regenerate the mirror INDEX from ``[(filename, fm), …]``: one line per
    note (``- [[slug]] — description``), grouped by ``type``. Deterministic (no
    timestamps) so an unchanged corpus produces byte-identical output."""
    by_type = {}
    for name, fm in published_meta:
        t = (fm.get("type") or "reference").strip() or "reference"
        slug = name[:-3] if name.endswith(".md") else name
        by_type.setdefault(t, []).append((slug, (fm.get("description") or "").strip()))
    lines = ["# INDEX — shared brain", "",
             "Auto-generated by the brain-station publish step. Do not edit here.", ""]
    for t in sorted(by_type):
        lines.append(f"## {t}")
        for slug, desc in sorted(by_type[t]):
            lines.append(f"- [[{slug}]]" + (f" — {desc}" if desc else ""))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _readme_content(owner):
    who = owner or "this private brain's owner"
    return (
        f"# Shared brain — {who}\n\n"
        f"> **Read-only for others.** This repository is {who}'s shared brain "
        "mirror, generated automatically by the brain-station `publish` step. "
        "Do not edit files here — edits belong in the owner's private vault and "
        "are overwritten on the next publish. Only the owner can write; everyone "
        "in the org can read.\n\n"
        "Generated-by: brain-station (brain.publish)\n")


def _git_is_repo(mirror):
    return (Path(mirror) / ".git").exists()


def _git_commit_all(mirror, msg):
    """Stage everything and commit the sync as ONE commit. Loud on real failure;
    a no-op (returns None) when there is nothing to commit. Never pushes."""
    m = str(mirror)
    add = subprocess.run(["git", "-C", m, "add", "-A"], capture_output=True, text=True)
    if add.returncode != 0:
        raise PublishError(f"git add failed in {m}: {add.stderr.strip()}")
    commit = subprocess.run(["git", "-C", m, "commit", "-m", msg], capture_output=True, text=True)
    if commit.returncode != 0:
        out = (commit.stderr or "") + (commit.stdout or "")
        if "nothing to commit" in out or "nothing added to commit" in out:
            return None
        raise PublishError(f"git commit failed in {m}: {out.strip()}")
    return msg


def run(cfg, *, mirror=None, owner=None, commit=True, today=None, withdraw=False):
    """Publish eligible vault notes into ``mirror``. Returns a summary dict:
    ``{status, published[slugs], blocked[(name, reasons)], removed[slugs],
    withdrawn[slugs], writes, committed}``. ``writes`` counts every file
    written/deleted — zero on an unchanged rerun (the idempotence contract).

    ``withdrawn`` lists mirror notes whose source is present and clean but no
    longer carries ``publish: true``. By default they are KEPT (and reported);
    ``withdraw=True`` deletes them, in which case they appear in BOTH
    ``withdrawn`` (what was dropped) and ``removed`` (what left the mirror)."""
    day = today or datetime.date.today().isoformat()
    summary = {"status": "ok", "published": [], "blocked": [],
               "removed": [], "withdrawn": [], "writes": 0, "committed": None}
    if not mirror:
        summary["status"] = "no-mirror"
        return summary

    vault = Path(cfg["vault"])
    mirror = Path(mirror)
    notes_dir = vault / "notes"
    if not notes_dir.exists():
        summary["status"] = "no-notes"
        return summary
    mirror.mkdir(parents=True, exist_ok=True)

    published_meta = []  # [(filename, fm)] for INDEX + deletion sweep
    for src in sorted(notes_dir.glob("*.md")):
        if src.stem.startswith("_"):
            # Internal bookkeeping (e.g. the promote queue) — never published.
            # Org-bound content lands org-readable only through the reviewed
            # promote PR, and every other notes/ consumer skips _-stems too.
            continue
        text = src.read_text(errors="ignore")
        fm, _ = notes.parse_note(text)
        if not _flag(fm, "publish"):
            continue  # opt-IN: no `publish: true`, no mirror copy
        reasons = lint_note(text)
        if reasons:
            # Loud skip — never transform the source silently; the run continues.
            summary["blocked"].append((src.name, reasons))
            continue
        data = src.read_bytes()
        dest = mirror / src.name
        if not dest.exists() or dest.read_bytes() != data:
            dest.write_bytes(data)          # byte-exact copy
            summary["writes"] += 1
        published_meta.append((src.name, fm))
        summary["published"].append(src.stem)

    # Deletion sweep — THREE cases, not one (see the module docstring):
    #   source GONE from notes/          -> delete   (true mirror semantics)
    #   source BLOCKED by publish-lint   -> delete   (a leak must come out)
    #   source clean but not marked      -> KEEP + report as `withdrawn`
    # The third case is what makes the opt-out→opt-in flip survivable: without
    # it the very next publish would erase the whole mirror, since no note
    # carries the new field yet.
    keep = {name for name, _ in published_meta}
    for m in sorted(mirror.glob("*.md")):
        if m.name in ("INDEX.md", "README.md") or m.name in keep:
            continue
        source = notes_dir / m.name
        # Row three — and ONLY row three — is the keep case, and the lint is
        # re-run here rather than reused off summary["blocked"] because an
        # UNMARKED source is never linted above (the gate skips it first). A
        # note that is both unmarked and dirty is a leak, and a leak comes out
        # whatever its switch says. `_`-stems were never publishable at all, so
        # a stray one in the mirror is a deletion too.
        withdrawn = (source.exists()
                     and not source.stem.startswith("_")
                     and not lint_note(source.read_text(errors="ignore")))
        if withdrawn:
            summary["withdrawn"].append(m.stem)
            if not withdraw:
                continue        # kept on purpose — reported, never dropped
        m.unlink()
        summary["writes"] += 1
        summary["removed"].append(m.stem)

    index_text = _index_content(published_meta)
    index_path = mirror / "INDEX.md"
    if not index_path.exists() or index_path.read_text(errors="ignore") != index_text:
        index_path.write_text(index_text)
        summary["writes"] += 1

    readme_path = mirror / "README.md"
    if not readme_path.exists():  # header written ONCE; a later hand-edit survives
        readme_path.write_text(_readme_content(owner))
        summary["writes"] += 1

    if commit and _git_is_repo(mirror):
        summary["committed"] = _git_commit_all(mirror, f"publish: {len(published_meta)} notes ({day})")
    return summary


def _print_summary(res, mirror):
    if res["status"] == "no-mirror":
        print("brain-publish: no mirror configured — nothing to do")
        return
    print(f"brain-publish: {len(res['published'])} published, "
          f"{len(res['blocked'])} blocked, {len(res['removed'])} removed -> {mirror}")
    for name, reasons in res["blocked"]:
        print(f"  ✗ BLOCKED {name}: {'; '.join(reasons)}")
    for slug in res["removed"]:
        print(f"  - removed {slug}")
    # Loud, one per line, with the exact command: a withdrawn note is the one
    # case where the run deliberately did NOT do what mirror semantics say.
    kept = [s for s in res.get("withdrawn", []) if s not in res["removed"]]
    if kept:
        print(f"  ! WITHDRAWN-BUT-KEPT {len(kept)} notes are in the mirror with no "
              "`publish: true` in the source:")
        for slug in kept:
            print(f"      - {slug}")
        print("    They were NOT deleted. Add `publish: true` to keep them, or "
              "re-run with --withdraw to remove them.")
    if res["committed"]:
        print(f"  committed: {res['committed']} (not pushed)")


def main(argv=None):
    ap = argparse.ArgumentParser(prog="brain-publish", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--mirror", help="override the publish mirror dir (default: config publish_mirror)")
    ap.add_argument("--owner", help="owner name/UPN for the mirror README header")
    ap.add_argument("--if-configured", action="store_true",
                    help="no-op unless a publish_mirror is EXPLICITLY configured "
                         "(env/config) — the /brain-heal auto-step uses this so the "
                         "brain never auto-publishes to an un-opted-in default location")
    ap.add_argument("--withdraw", action="store_true",
                    help="ALSO delete mirror notes whose source is present and clean "
                         "but no longer carries `publish: true`. Without this they are "
                         "kept and reported — a default run never un-publishes silently")
    ap.add_argument("--quiet", action="store_true")
    a = ap.parse_args(argv)

    config.require_valid()  # reads the vault; refuse a silently-defaulted one
    cfg = config.load()
    if a.if_configured and not a.mirror and not config.publish_mirror_configured():
        if not a.quiet:
            # the env name is read off config.ENV so the hint cannot drift from
            # the key publish_mirror_configured() actually consults.
            print("brain-publish: no publish_mirror configured — skipping (set "
                  f"publish_mirror or {config.ENV['publish_mirror']} to enable)")
        return 0
    mirror = a.mirror or cfg["publish_mirror"]
    if not cfg["vault"].exists():
        if not a.quiet:
            print(f"brain-publish: vault missing at {cfg['vault']} — run /brain-init")
        return 0
    res = run(cfg, mirror=mirror, owner=a.owner, withdraw=a.withdraw)
    if not a.quiet:
        _print_summary(res, mirror)
    return 0


if __name__ == "__main__":  # pragma: no cover — Phase 5 owns the entry point
    sys.exit(main())
