#!/usr/bin/env bash
# SessionStart hook: surface open tasks (or the already-attached task) so Claude
# can recognise a resume. Emitted as SessionStart additionalContext JSON.
input=$(cat)
# Suppressed inside delegate-spawned workers — task tracking is the hub's job.
[ -n "$TASK_STATION_SUPPRESS" ] && exit 0
session_id=$(echo "$input" | jq -r '.session_id // "unknown"')
source=$(echo "$input" | jq -r '.source // ""')

# Publish a stable, version-independent handle to this plugin so non-plugin
# callers (delegate invocations, the status line) don't chase the versioned
# plugin-cache dir. Refreshed every session, so it self-heals across updates.
if [ -n "$CLAUDE_PLUGIN_ROOT" ]; then
  _cfg="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
  ln -sfn "$CLAUDE_PLUGIN_ROOT/lib" "$_cfg/task-station-engine" 2>/dev/null
  # Self-register a composable status-line segment. The plugin path is frozen
  # in at write time (re-frozen each session) because $CLAUDE_PLUGIN_ROOT does
  # not resolve in the status-line command context.
  mkdir -p "$_cfg/statusline.d" 2>/dev/null
  cat > "$_cfg/statusline.d/50-task-station.sh" <<SEG 2>/dev/null
#!/usr/bin/env bash
# Auto-generated by task-station SessionStart; do not edit (regenerated each session).
sid=\$(python3 -c 'import sys,json; print(json.load(sys.stdin).get("session_id",""))' 2>/dev/null)
[ -n "\$sid" ] || exit 0
exec python3 "$CLAUDE_PLUGIN_ROOT/lib/task-station.py" whoami --session "\$sid" --statusline --width "\${TASK_STATION_STATUSLINE_WIDTH:-0}"
SEG
  chmod +x "$_cfg/statusline.d/50-task-station.sh" 2>/dev/null
fi

if [ -n "$CLAUDE_PLUGIN_ROOT" ] && [ "$(python3 "$CLAUDE_PLUGIN_ROOT/lib/task-station.py" config --bare-cmds-get 2>/dev/null)" = "on" ]; then
  _cmds="${CLAUDE_CONFIG_DIR:-$HOME/.claude}/commands"; mkdir -p "$_cmds" 2>/dev/null
  for c in todo done; do
    _dst="$_cmds/$c.md"; _src="$CLAUDE_PLUGIN_ROOT/commands/$c.md"
    if [ ! -e "$_dst" ] || head -1 "$_dst" 2>/dev/null | grep -q 'task-station-managed'; then
      { printf '%s\n' "<!-- task-station-managed: bare alias for /task-station:$c -->";
        sed 's#${CLAUDE_PLUGIN_ROOT}/lib#'"${CLAUDE_CONFIG_DIR:-$HOME/.claude}"'/task-station-engine#g' "$_src"; } > "$_dst" 2>/dev/null
    fi
  done
fi

ctx=$(python3 "${CLAUDE_PLUGIN_ROOT}/lib/task-station.py" session-start --session "$session_id" --source "$source")
_seen="${TASK_STATION_HOME:-${CLAUDE_CONFIG_DIR:-$HOME/.claude}/task-station-data}/.setup-nudged"
nudge=""
if [ ! -e "$_seen" ] && [ -n "$CLAUDE_PLUGIN_ROOT" ]; then
  if [ -z "$(python3 "$CLAUDE_PLUGIN_ROOT/lib/task-station.py" config --workspace-dirs-get 2>/dev/null)" ]; then
    nudge='task-station installed. Finish optional setup any time with `task-station setup`.'
  fi
  mkdir -p "$(dirname "$_seen")" 2>/dev/null; : > "$_seen"
fi
[ -n "$nudge" ] && ctx="${ctx}${ctx:+$'\n'}$nudge"

# Auto-label the window for an attached task (task-station-<seq> · <title>) — the hub can't
# be programmatically renamed, but its title CAN be set via the SessionStart hook.
title=$(python3 "${CLAUDE_PLUGIN_ROOT}/lib/task-station.py" session-title --session "$session_id")
if [ -n "$ctx" ] || [ -n "$title" ]; then
  jq -n --arg c "$ctx" --arg t "$title" \
    '{hookSpecificOutput: ({hookEventName: "SessionStart"}
        + (if $c != "" then {additionalContext: $c} else {} end)
        + (if $t != "" then {sessionTitle: $t} else {} end))}'
fi
exit 0
